### ISSUE TITLE
Application check in update callback api

### ISSUE THREAD

**Issue by jnpsk** [lime-company/powerauth-server#1100]
`/application/callback/update` expects `callbackId` of the callback url to edit and `applicationId` of the application to which the callback is assigned. There should be a check during the update to validate the passed `applicationId` corresponds to the right application owning the callback.

If the `callbackId` belongs to a different application, throw an exception.

**Comment by jnpsk** [comment]
Related to https://github.com/wultra/powerauth-cloud/issues/579
When updating callback using `/application/callback/update`, two parameters are needed:
- `callbackId` -- the id of the callback in database
- `applicationId` --  the id of the application that owns the callback

If the passed `applicationId` does not own the callback with specified `callbackId`, throw an exception.

**Comment by kopovan** [comment]
tested here: https://github.com/wultra/powerauth-cloud/issues/579#issuecomment-1843258045
