### ISSUE TITLE
Implement support for offline signatures

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-server#13]
We need to refactor SignatureServiceBehavior to split verifySignature() method into smaller methods. 

We also need to prepare XSD definition for offline signature requests/responses and prepare REST and SOAP endpoints for offline signature.

Following methods are required for offline signature:
* createOfflineSignaturePayload
* verifyOfflineSignature

Related issues:
https://github.com/lime-company/mtoken-ios/issues/22
https://github.com/lime-company/powerauth-webflow/issues/33

**Comment by petrdvorak** [comment]
Already fixed.
