### ISSUE TITLE
Enforce presence of user ID before operation approval

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-server#1771]
Operations which do not have `userId` specified when created should be always claimed before approval. Operation approval should reject operations without `userId`. Implement operation claim for FIDO2 as part of this request to allow this check.

**Comment by zcgandcomp** [comment]
Are we going to change the rejectOperation as well? 
It is not necessary from the functional point of view, but it will follow the same pattern as approval—i.e., the user needs to claim the operation before approval and rejection.
Of course, proper impact analysis would have to be done first - to mitigate any side effects.

**Comment by romanstrobl** [comment]
Good point, I will review `rejectOperation`, too.
