### ISSUE TITLE
Application level record encryption

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-server#39]
At the moment, we store device related server private key as a plain text in the database. This is not a big issue in some scenarios, since back-ends are in a secure infrastructure with very limited access, however we could still improve security of the key by:

1. Introducing a new property (in case the property is not set, no encryption is used):

```
powerauth.server.db.master.encryption.key=MTIzNDU2Nzg5MDEyMzQ1Ng==
```

2. Using conversion mechanism whenever loading a `serverPrivateKey` value for the activation entity.

Note that since there is the good old rule "Same data should result in different encrypted values", we should introduce IV value for the encryption that should be stored with the value, such as (pseudo-code):

```java
public byte[] encrypt(byte[] orig, SecretKey key) {
    byte[] iv = Bytes.random(16);
    byte[] encrypted = aes.encrypt(orig, iv, key);
    byte[] record = iv.append(encrypted)
    return record;
}

public byte[] decrypt(byte[] record, SecretKey key) {
    byte[] iv = record.byteRange(0, 16); // offset, length
    byte[] encrypted = record.byteRange(16, -1); // offset, remaining
    byte[] orig = aes.decrypt(encrypted, iv, key);
    return orig;
}
```

Also, in order to achieve consistency between activation record and encrypted server private key (to avoid partial record swap), we should pay attention to how we construct the encryption key. It should be derived from the master DB encryption key using [KDF_INTERNAL](https://github.com/lime-company/powerauth-crypto/wiki/Basic-definitions) with user ID and activation ID derivate as a base, like so:

```java
public SecretKey deriveSecretKey(SecretKey masterDbEncryptionKey, String userId, String activationId) {
    String base = activationId.getBytes("UTF-8");
    String salt = userId.getBytes("UTF-8");
    byte[] index = PBKDF2.expand(base, salt, iterations, lengthInBits);
    return KDF_INTERNAL.derive(masterDbEncryptionKey, index);
}
```

Since we need entity context in order to achieve this, we very likely aren't able to use (aspect / annotation based) converter...

**Comment by hvge** [comment]
I just had a discussion with @romanstrobl and I think that this scheme is wrong. IMHO the performance impact is too big and unacceptable.

**Comment by hvge** [comment]
Roman found a better attack. Just asking for an activation status (e.g. you need just one valid activation), can overload the server 🥇

**Comment by romanstrobl** [comment]
I looked at activation the locks once again and you would need multiple activations to perform the DOS attack, the read requests get blocked in PESSIMISTIC_WRITE, too. 

We still have a performance problem, because PBKDF2 derivation is used in all these case:
* Get activation status
* Get personalized encryption key
* Validate signature
* Create personalized offline signature payload
* Vault unlock

It is quite clear that we should avoid using PBKDF2 per activation, otherwise the performance impact is too large.

**Comment by romanstrobl** [comment]
The performance issues were resolved by removing PBKDF2 derivation function. We still need to prepare a migration tool / integrate migration support into PowerAuth - I suggest to handle this task in a separate issue.
