### ISSUE TITLE
Consider handling off-line QR code signatures without dash characters

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-server#70]
PowerAuth Server currently accepts offline signatures in following format: `AAAABBBB-CCCCDDDD`. For readability reasons, we render it as `AAAA-BBBB-CCCC-DDDD` and this is what user rewrites to the screen. We should consider ignoring dashes when validating off-line signatures.

**Comment by romanstrobl** [comment]
The signature validation implementation is located in PowerAuth Crypto.

See:

https://github.com/lime-company/powerauth-crypto/blob/develop/powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/SignatureUtils.java#L123

And:
https://github.com/lime-company/powerauth-crypto/blob/develop/powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/SignatureUtils.java#L137

I suggest we remove the dash from both computed and received signatures for the signature comparison. Do you agree?

**Comment by romanstrobl** [comment]
We considered this change and decided to keep the single dash in the signature. The offline signatures should be converted to format AAAABBBB-CCCCDDDD from any other user-friendly syntax. AAAABBBB is related to the first factor, CCCCDDDD is related to the second factor.
