### ISSUE TITLE
Prepare migration script and documentation for Oracle sequences

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-server#97]
We are deprecating usage of HIBERNATE_SEQUENCE in PowerAuth server in favor of per-table sequences.

We should prepare a PL/SQL migration script and document the migration. The migration script needs to take into account current sequence value, so that there is no ID conflict.

**Comment by romanstrobl** [comment]
Here is a sample PL/SQL script we can use. One parameter we should discuss is a safety buffer for the next value used in newly created sequences. I assume the migration script will be executed while PowerAuth is running and then the new version of PowerAuth will be deployed relatively soon after the DB migration was completed. However there is still some time during which the old sequence value can increase. Thus I suggest to increment the last known sequence value with some large enough constant.

Example:

```sql
declare
  old_val INTEGER;
begin
  select (hibernate_sequence.nextval) + 10000
  into old_val
  from dual;

  execute immediate 'create sequence new_seq start with ' || old_val || ' increment by 1';
end;
/
```

**Comment by petrdvorak** [comment]
Looks reasonable.
